Corporate/Controllers/AccountingController.cs
using Corporate.Models;
using Corporate.ViewModel;
using Dapper;
using Microsoft.Reporting.WinForms;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace Corporate.Controllers
{
    public class AccountingController : Controller
    {
        //
        // GET: /Accounting/
        LedgerBook obj = new LedgerBook();
        public ActionResult Index()
        {
            string query = Request.QueryString["route"];
            string Param;

            if (query == null)
            {
                Param = "null";
            }
            else
            {
                Param = query;
            }


            IEnumerable<LedgerVM> data = (IEnumerable<LedgerVM>)obj.GetLedger(Param);
            return View(data);
        }

        public ActionResult Payment()
        {

            string search = Request.QueryString["query"];
            string query = Request.QueryString["route"];
            string Param;

            if (query == null)
            {
                Param = "null";
            IEnumerable<PaymentVM> data = (IEnumerable<PaymentVM>)obj.GetPayments(Param);
            if (search == null)
            {
                return View(data);
            }
            else
            {
                return View(data.Where(x => x.PaymentType == search));
            }
            
            }
            else
            {
                Param = query;
                IEnumerable<PaymentVM> data = (IEnumerable<PaymentVM>)obj.GetPayments(Param);
                if (search == null)
                {
                    return View(data);
                }
                else
                {
                    return View(data.Where(x => x.PaymentType == search));
                }
                
            }
        }
        [HttpPost]
        public JsonResult Save(PaymentDetail pay)
        {
            CorparateResult<PaymentDetail> data = obj.AddPayment(pay);
            bool reply = data.Exist;
            string msg = data.Message;
            return new JsonResult { Data = new { Respond = reply, Message = msg }, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public ActionResult PaymentDetail(int RecieptID, DateTime Date)
        {
            var data = obj.PaymentDetail(RecieptID);
            return View(data.GenericList);

        }
        public ActionResult PaymentReport(string PurchaserID, string FromDate, string ToDate)
        {
            string path="";
           //urchaserID = PurchaserID.ToString();
            if (PurchaserID == "null")
            {
                PurchaserID = "null";
                path = Server.MapPath("~/Reports/AllPayment.rdlc");
            }
            if (FromDate == "" || ToDate == "")
            {
                FromDate = "null";
                ToDate = "null";
                if (PurchaserID == "null")
                {
                    path = Server.MapPath("~/Reports/AllPayment.rdlc");
                }
                else
                {
                    path = Server.MapPath("~/Reports/PaymentReport.rdlc");
                }
            }
          
            LocalReport lr = new LocalReport();
           
            if (System.IO.File.Exists(path))
            {
                lr.ReportPath = path;
            }
            else
            {
                return View("Index");
            }
            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionStringOld"].ToString()))
            {
                var para = new DynamicParameters();
                para.Add("@Purchaser", PurchaserID);
                para.Add("@StartDate", FromDate);
                para.Add("@EndDate", ToDate);
                var data = con.Query<PaymentVM>("PaymentStatementByDate", para, null, true, 0, CommandType.StoredProcedure).ToList();
                ReportDataSource rd;
                if (PurchaserID == "null")
                {
                    rd = new ReportDataSource("AllPaymentDS", data.ToList());
                }
                else
                {
                   rd = new ReportDataSource("PaymentReportDS", data.ToList());
                }
                // var go = (from a in db.PaymentStatementByDate("null","null","null) select a);
               // ReportDataSource rd = new ReportDataSource("AllPaymentDS", data.ToList());
                lr.DataSources.Add(rd);
                string OrderNo = "Pay";
                string reportType = "PDF";
                string mimeType;
                string encoding;
                string fileNameExtension;
                var dateAndTime = DateTime.Now;
                var date = dateAndTime.Date;
                string deviceinfo = "<DeviceInfo>" + "<OutputFormat>PDF</OutputFormat>" +
                    "<PageWidth>7.5in</PageWidth>" +
                    "<PageHeight>11in</PageHeight>" +
                    "<MarginTop>0.2in</MarginTop>" +
                    "<MarginLeft>0.3in</MarginLeft>" +
                    "<MarginRight>0.3in</MarginRight>" +
                      "<MarginBottom>0.5in</MarginBottom></DeviceInfo>";
                byte[] RenderedBytes;
                string[] streams;
                Warning[] warnings;
                RenderedBytes = lr.Render(reportType, deviceinfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
                //For download option Commet to stop for download below
                Response.Buffer = true;
                Response.Clear();
                Response.ContentType = mimeType;
                Response.AddHeader("content-disposition", "attachment; filename=" + OrderNo + "_" + date.ToString("dd/MM/yyyy") + "." + fileNameExtension);
                Response.BinaryWrite(RenderedBytes); // create the file
                Response.Flush();
                //End download option
                return File(RenderedBytes, mimeType);
            }
        }

        public JsonResult GetBalance(string ID)
        {
            var data = obj.GetBalance(ID);

            return new JsonResult { Data = new {Bal= data }, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public ActionResult PaymentReceipt(string OrderNo)
        {
            LocalReport lr = new LocalReport();
            string path = Server.MapPath("~/Reports/PaymentReceipt.rdlc");
            if (System.IO.File.Exists(path))
            {
                lr.ReportPath = path;
            }
            else
            {
                return View("Index");
            }
            using (ConnectionString db = new ConnectionString())
            {
                db.Configuration.LazyLoadingEnabled = false;
                var go = (from a in db.Generate_PaymentReceipt(OrderNo) select a);
                ReportDataSource rd = new ReportDataSource("PaymentReceiptDS", go.ToList());
                lr.DataSources.Add(rd);
                string reportType = "PDF";
                string mimeType;
                string encoding;
                string fileNameExtension;
                var dateAndTime = DateTime.Now;
                var date = dateAndTime.Date;
                string deviceinfo = "<DeviceInfo>" + "<OutputFormat>PDF</OutputFormat>" +
                    "<PageWidth>7.5in</PageWidth>" +
                    "<PageHeight>5.5in</PageHeight>" +
                    "<MarginTop>0.2in</MarginTop>" +
                    "<MarginLeft>0.3in</MarginLeft>" +
                    "<MarginRight>0.3in</MarginRight>" +
                      "<MarginBottom>0.1in</MarginBottom></DeviceInfo>";
                byte[] RenderedBytes;
                string[] streams;
                Warning[] warnings;
                RenderedBytes = lr.Render(reportType, deviceinfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
                //For download option Commet to stop for download below
                Response.Buffer = true;
                Response.Clear();
                Response.ContentType = mimeType;
                Response.AddHeader("content-disposition", "attachment; filename=" + "PaymentReceipt" + OrderNo + "_" + date.ToString("dd/MM/yyyy") + "." + fileNameExtension);
                Response.BinaryWrite(RenderedBytes); // create the file
                Response.Flush();
                //End download option
                return File(RenderedBytes, mimeType);
            }
        }
    }
}

Corporate/Controllers/OrderController.cs
using Corporate.Models;
using Corporate.ViewModel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Corporate.Controllers
{
    public class OrderController : Controller
    {
        //
        // GET: /Order/
       Inventory obj = new Inventory();
        public ActionResult Orders()
        {
            return View();
        }

        public ActionResult GetStock()
        {
          IEnumerable<ShowInventoryVM> data =obj.GetStock("null","null");
         // var s = data.Count(e => e.Quantity);
            return View(data);
           
        }
    }
}

Corporate/Views/Shared/_Layout.cshtml
@using Corporate.Models;
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
     <link href="~/Images/logo.ico" rel="shortcut icon" type="image/x-icon" />
        <script src="~/Bootstrap/js/bootstrap.min.js"></script>
    <title>@ViewBag.Title</title>
 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="~/Bootstrap/css/bootstrap.min.css" rel="stylesheet">
       <link href="~/Bootstrap/css/bootstrap-theme.css" rel="stylesheet">
       <link href="~/Bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Styles/Default.css" rel="stylesheet">
         <link href="~/Styles/Custom.css" rel="stylesheet">
       <link href="~/Styles/popModal.css" rel="stylesheet">
      <script src="~/Scripts/popModal.js"></script>

      <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css" rel="stylesheet">
  </head>

  <body>
      
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" style="color:white">
      <div class="container">
        @*  <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                  <span class="sr-only">Toggle Navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand">NSE Trading</a>
          </div>*@
          <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                 @* <li class="active">Home</li>
                   <li class="active">Gallery</li>
                   <li class="active">About US</li>*@
              </ul>
              <div class="nav navbar-nav navbar-right">
                 <h3><u>@{UserInfo userinfo = UserInfo.GetInstence; if(userinfo != null)
    {<text>Welcome </text> @userinfo.UserFullName}}
                    </u></h3>
           <a  data-toggle="modal" data-target="#logout" style="cursor:pointer">Logout</a>
       </div>
          </div><!-- End nav collapse-->
      </div>


         
     @* <a class="navbar-brand" ><h3><u>@if(Session["FullName"] != null)
    {<text>Welcome </text> @Session["FullName"]}
                    </u></h3></a>
      <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
   
      </div>*@
            
    </nav>

    <div class="container-fluid">
      <div class="row" >
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar" style="margin-top:-49px;">
          <ul class="nav nav-pills flex-column">
            
            <li class="nav-item">
              @Html.ActionLink("DashBoard", "DashBoard", "Account", null, new {style="text-decoration:none"})@*,@class="glyphicon glyphicon-user"})*@
            </li>
            <li class="nav-item">
              @Html.ActionLink("Orders", "Orders", "Order", null, new {style="text-decoration:none"})@*,@class="glyphicon glyphicon-user"})*@
            </li>
            <li class="nav-item">
            @Html.ActionLink("Ledger", "Index", "Accounting", null, new {style="text-decoration:none"})@*,@class="glyphicon glyphicon-user"})*@
            </li>
               <li class="nav-item">
            @Html.ActionLink("Configuration", "ConfigSetUp", "Setting", null, new {style="text-decoration:none"})@*,@class="glyphicon glyphicon-user"})*@
            </li>
                <li class="nav-item">
              @Html.ActionLink("Show Inventory", "GetStock", "Order", null, new {style="text-decoration:none"})@*,@class="glyphicon glyphicon-user"})*@
            </li>
          </ul>

          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="#">Nav item</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Nav item again</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">One more nav</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Another nav item</a>
            </li>
          </ul>

          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="#">Nav item again</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">One more nav</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Another nav item</a>
            </li>
          </ul>
        </nav>

        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main">
               @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>      
        </main>
      </div>
    </div>

      <script>
          $('#demo').click(function () {
              var st = 'succesfull';
              $('#Response').append('<i class="glyphicon glyphicon-trash"></i><p>' + st + '</p>');
             // $('#kam').text('sas'); 
             
              $('#Response').notifyModal({
                  duration: 2500,
                  placement: 'center',
                  onTop: true,
              });
              $('#Response').text('');
          });


</script>
  @*   @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)*@
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
      <script src="~/Scripts/jquery-1.11.2.js"><\/script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Bootstrap/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug 
    <script src="../../../../assets/js/ie10-viewport-bug-workaround.js"></script>-->
      <script>
          $(document).on("click", "#btnLogout", function (event) {
              $.ajax({
                  type: "POST",
                  url: '/Account/LogOut',
                  success: function (data) {
                      product = data;
                      window.location.href = 'http://localhost:1795/Account/Login';
                  },
                  error: function (error) {
                      console.log(error);
                  }
              })
          });

      </script>

      <!-- Modal -->
<div class="modal fade" id="logout" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
       @* <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>*@
        <h4 class="modal-title" id="myModalLabel">Confirmation</h4>
      </div>
      <div class="modal-body">
      <b>Are you sure to want Logout?</b>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" id="btnLogout" class="btn btn-primary">Yes Logout</button>
      </div>
    </div>
  </div>
</div>
  </body>
</html>





