Corporate/Controllers/AccountingController.cs
using Corporate.Models;
using Corporate.ViewModel;
using Dapper;
using Microsoft.Reporting.WinForms;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace Corporate.Controllers
{
    public class AccountingController : Controller
    {
        //
        // GET: /Accounting/
        LedgerBook obj = new LedgerBook();
        public ActionResult Index()
        {
            string query = Request.QueryString["route"];
            string Param;

            if (query == null)
            {
                Param = "null";
            }
            else
            {
                Param = query;
            }


            IEnumerable<LedgerVM> data = (IEnumerable<LedgerVM>)obj.GetLedger(Param);
            return View(data);
        }

        public ActionResult Payment()
        {

            string search = Request.QueryString["query"];
            string query = Request.QueryString["route"];
            string Param;

            if (query == null)
            {
                Param = "null";
            IEnumerable<PaymentVM> data = (IEnumerable<PaymentVM>)obj.GetPayments(Param);
            if (search == null)
            {
                return View(data);
            }
            else
            {
                return View(data.Where(x => x.PaymentType == search));
            }
            
            }
            else
            {
                Param = query;
                IEnumerable<PaymentVM> data = (IEnumerable<PaymentVM>)obj.GetPayments(Param);
                if (search == null)
                {
                    return View(data);
                }
                else
                {
                    return View(data.Where(x => x.PaymentType == search));
                }
                
            }
        }
        [HttpPost]
        public JsonResult Save(PaymentDetail pay)
        {
            CorparateResult<PaymentDetail> data = obj.AddPayment(pay);
            bool reply = data.Exist;
            string msg = data.Message;
            return new JsonResult { Data = new { Respond = reply, Message = msg }, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public ActionResult PaymentDetail(int RecieptID, DateTime Date)
        {
            var data = obj.PaymentDetail(RecieptID);
            return View(data.GenericList);

        }
        public ActionResult PaymentReport(string PurchaserID, string FromDate, string ToDate)
        {
            string path="";
           //urchaserID = PurchaserID.ToString();
            if (PurchaserID == "null")
            {
                PurchaserID = "null";
                path = Server.MapPath("~/Reports/AllPayment.rdlc");
            }
            if (FromDate == "" || ToDate == "")
            {
                FromDate = "null";
                ToDate = "null";
                if (PurchaserID == "null")
                {
                    path = Server.MapPath("~/Reports/AllPayment.rdlc");
                }
                else
                {
                    path = Server.MapPath("~/Reports/PaymentReport.rdlc");
                }
            }
          
            LocalReport lr = new LocalReport();
           
            if (System.IO.File.Exists(path))
            {
                lr.ReportPath = path;
            }
            else
            {
                return View("Index");
            }
            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionStringOld"].ToString()))
            {
                var para = new DynamicParameters();
                para.Add("@Purchaser", PurchaserID);
                para.Add("@StartDate", FromDate);
                para.Add("@EndDate", ToDate);
                var data = con.Query<PaymentVM>("PaymentStatementByDate", para, null, true, 0, CommandType.StoredProcedure).ToList();
                ReportDataSource rd;
                if (PurchaserID == "null")
                {
                    rd = new ReportDataSource("AllPaymentDS", data.ToList());
                }
                else
                {
                   rd = new ReportDataSource("PaymentReportDS", data.ToList());
                }
                // var go = (from a in db.PaymentStatementByDate("null","null","null) select a);
               // ReportDataSource rd = new ReportDataSource("AllPaymentDS", data.ToList());
                lr.DataSources.Add(rd);
                string OrderNo = "Pay";
                string reportType = "PDF";
                string mimeType;
                string encoding;
                string fileNameExtension;
                var dateAndTime = DateTime.Now;
                var date = dateAndTime.Date;
                string deviceinfo = "<DeviceInfo>" + "<OutputFormat>PDF</OutputFormat>" +
                    "<PageWidth>7.5in</PageWidth>" +
                    "<PageHeight>11in</PageHeight>" +
                    "<MarginTop>0.2in</MarginTop>" +
                    "<MarginLeft>0.3in</MarginLeft>" +
                    "<MarginRight>0.3in</MarginRight>" +
                      "<MarginBottom>0.5in</MarginBottom></DeviceInfo>";
                byte[] RenderedBytes;
                string[] streams;
                Warning[] warnings;
                RenderedBytes = lr.Render(reportType, deviceinfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
                //For download option Commet to stop for download below
                Response.Buffer = true;
                Response.Clear();
                Response.ContentType = mimeType;
                Response.AddHeader("content-disposition", "attachment; filename=" + OrderNo + "_" + date.ToString("dd/MM/yyyy") + "." + fileNameExtension);
                Response.BinaryWrite(RenderedBytes); // create the file
                Response.Flush();
                //End download option
                return File(RenderedBytes, mimeType);
            }
        }

        public JsonResult GetBalance(string ID)
        {
            var data = obj.GetBalance(ID);

            return new JsonResult { Data = new {Bal= data }, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public ActionResult PaymentReceipt(string OrderNo)
        {
            LocalReport lr = new LocalReport();
            string path = Server.MapPath("~/Reports/PaymentReceipt.rdlc");
            if (System.IO.File.Exists(path))
            {
                lr.ReportPath = path;
            }
            else
            {
                return View("Index");
            }
            using (ConnectionString db = new ConnectionString())
            {
                db.Configuration.LazyLoadingEnabled = false;
                var go = (from a in db.Generate_PaymentReceipt(OrderNo) select a);
                ReportDataSource rd = new ReportDataSource("PaymentReceiptDS", go.ToList());
                lr.DataSources.Add(rd);
                string reportType = "PDF";
                string mimeType;
                string encoding;
                string fileNameExtension;
                var dateAndTime = DateTime.Now;
                var date = dateAndTime.Date;
                string deviceinfo = "<DeviceInfo>" + "<OutputFormat>PDF</OutputFormat>" +
                    "<PageWidth>7.5in</PageWidth>" +
                    "<PageHeight>5.5in</PageHeight>" +
                    "<MarginTop>0.2in</MarginTop>" +
                    "<MarginLeft>0.3in</MarginLeft>" +
                    "<MarginRight>0.3in</MarginRight>" +
                      "<MarginBottom>0.1in</MarginBottom></DeviceInfo>";
                byte[] RenderedBytes;
                string[] streams;
                Warning[] warnings;
                RenderedBytes = lr.Render(reportType, deviceinfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
                //For download option Commet to stop for download below
                Response.Buffer = true;
                Response.Clear();
                Response.ContentType = mimeType;
                Response.AddHeader("content-disposition", "attachment; filename=" + "PaymentReceipt" + OrderNo + "_" + date.ToString("dd/MM/yyyy") + "." + fileNameExtension);
                Response.BinaryWrite(RenderedBytes); // create the file
                Response.Flush();
                //End download option
                return File(RenderedBytes, mimeType);
            }
        }
    }
}

Corporate/Controllers/POController.cs
using Corporate.Models;
using Corporate.ViewModel;
using Microsoft.Reporting.WinForms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace Corporate.Controllers
{
    public class POController : Controller
    {
        //
        // GET: /PO/
        PO obj = new PO();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreatePO()
        {
            string query = Request.QueryString["route"];
            string Param;

            if (query == null)
            {
                Param = "null";
            }
            else
            {
                Param = query;
            }

            IEnumerable<POGridVM> data = (IEnumerable<POGridVM>)obj.GetAllPO(Param);
            return View(data);
           
        }
        public ActionResult ViewOrderDetails(int OrderID,string Mini, string Macro, DateTime Date)
        {
            var data = obj.ViewOrderDetails(OrderID);
          //  data.GenericList[0].OrderNo = OrderNo;
            return View(data.GenericList);

        }
        [HttpPost]
        public JsonResult CreateOrder(OrderMaster pur)
        {
            CorparateResult<OrderMaster> data = obj.Save(pur);
            bool reply = data.Exist;
            string msg = data.Message;

            return new JsonResult { Data = new { Respond = reply, Message = msg }, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getOrderType()
        {
            CorparateResult<DropDownVM> data = obj.getPaymentType();
            return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getPurchaser()
        {
            CorparateResult<DropDownVM> data = obj.getPurchaser();
            ViewData["Firm"] = data;
            return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public JsonResult getCategories()
        {
            CorparateResult<DropDownVM> data = obj.getCategories();
            return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public JsonResult getProducts(int CatID)
        {
            CorparateResult<DropDownVM> data = obj.getProducts(CatID);
            return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public ActionResult Purchase_Invoice(string OrderNo)
        {
            LocalReport lr = new LocalReport();
            string path = Server.MapPath("~/Reports/PurchaseOrder.rdlc");
            if (System.IO.File.Exists(path))
            {
                lr.ReportPath = path;
            }
            else
            {
                return View("Index");
            }
            using (ConnectionString db = new ConnectionString())
            {
                db.Configuration.LazyLoadingEnabled = false;
                var go = (from a in db.Generate_POInvoice(OrderNo) select a);
                ReportDataSource rd = new ReportDataSource("POInvoiceDSet", go.ToList());
                  lr.DataSources.Add(rd);
                string reportType = "PDF";
                string mimeType;
                string encoding;
                string fileNameExtension;
                var dateAndTime = DateTime.Now;
                var date = dateAndTime.Date;
                string deviceinfo = "<DeviceInfo>" + "<OutputFormat>PDF</OutputFormat>" +
                    "<PageWidth>7.5in</PageWidth>" +
                    "<PageHeight>11in</PageHeight>" +
                    "<MarginTop>0.2in</MarginTop>" +
                    "<MarginLeft>0.3in</MarginLeft>" +
                    "<MarginRight>0.3in</MarginRight>" +
                      "<MarginBottom>0.5in</MarginBottom></DeviceInfo>";
                byte[] RenderedBytes;
                string[] streams;
                Warning[] warnings;
                RenderedBytes = lr.Render(reportType, deviceinfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
                //For download option Commet to stop for download below
                Response.Buffer = true;
                Response.Clear();
                Response.ContentType = mimeType;
                Response.AddHeader("content-disposition", "attachment; filename=" + OrderNo + "_" + date.ToString("dd/MM/yyyy") + "." + fileNameExtension);
                Response.BinaryWrite(RenderedBytes); // create the file
                Response.Flush();
                //End download option
                return File(RenderedBytes, mimeType);
            }
        }

    }
}

Corporate/Views/Accounting/Index.cshtml
@{
    ViewBag.Title = "Ledger";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using Corporate.ViewModel;
@model IEnumerable<LedgerVM>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>


<script>
    var Purchaser = [];
    function LoadPurchaser(element) {


        if (Purchaser.length == 0) {
            $.ajax({
                type: "GET",
                url: '/PO/getPurchaser',
                dataType: "json",
                success: function (data) {
                    //alert(JSON.stringify(data));
                    Purchaser = data.GenericList;

                    $.each(Purchaser, function (i, v) {
                        $('#DDPurchaser').append('<option value="' + v.Value + '">' + v.Text + '</option>');
                        //  $ele.append($('<option/>').val(v.CategoryID).text(v.CategoryName));

                    })
                    $.each(Purchaser, function (i, v) {
                        $('#firm').append('<option value="' + v.Value + '">' + v.Text + '</option>');
                        //  $ele.append($('<option/>').val(v.CategoryID).text(v.CategoryName));

                    })
                },
                error: function (Error) { console.log(Error); alert('err'); }
            })

        }
        else {
            renderCategory(element);
        }
    }
    function RedirectById(id) {
        if (id != 'All') {
            window.location.href = 'http://localhost:1795/Accounting/Index?route=' + id;
        }
        else {
            window.location.href = 'http://localhost:1795/Accounting/Index';
        }

    }
    LoadPurchaser(this);
</script>
<header id="headerz1">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="BGHeader"><span class="glyphicon glyphicon-pawn" aria-hidden="true"></span>Ledger</h2>
            </div>
        </div>
    </div>
    <div id="Response" style="display:none">
                  <p id="ResponseMsg"></p>
          </div> 
</header>
@*start of grid*@
<div class="col-md-12 row" >
    @using (Html.BeginForm("CreatePO")){
  
    <div class="col-md-6"><label for="gender" class="control-label col-md-12">Get by Firm</label></div>
          <div class="col-md-6"> <select class="form-control" id="firm" onchange = "RedirectById(this.value)" ><option value="">--Select--</option>
              <option value="All">Get All</option></select>
        </div>
    }
           </div><div class="clearfix"></div><br/>
<div class="panel panel-default">
    <div class="panel-heading text-center">
        <h3 class="panel-title"><b><u>Ledger Book</u></b></h3>
       
    </div>
    <div class="panel-body ">

        <table class="table table-responsive  table-hover">
            <thead>
                <tr>
                    <th>S.No</th>
                    <th>Transaction Date</th>
                    <th>Firm</th>
                      <th>OrderNo/RecieptNo</th>
                    <th>Credit</th>
                    <th>Debit</th>
                    <th>Balance</th>
                
                </tr>
            </thead>
            <tbody>
                @{int counter = 0;
               foreach (LedgerVM pur in @Model)
               {
                   counter=counter+1;
                    <tr>
                        <td>@counter</td>
                        <td>@pur.Date</td>
                         <td>@pur.Firm</td>
                       <td> @if(@pur.OrderNo != null)
                        {
                         @Html.ActionLink(@pur.OrderNo,"ViewOrderDetails","PO",
     new {@OrderID = @pur.OrderID, @Mini = @pur.OrderNo, @Macro = @pur.Debit, @Date = pur.Date  },null )
                        }
                          else if (@pur.PaymentDetailId != null)
                         
                        {
                         @Html.ActionLink(@pur.PaymentDetailId.ToString(),"PaymentDetail","Accounting",
     new {@RecieptID = @pur.PaymentDetailId, @Date = pur.Date  },null)
                        }</td>
                        <td>@pur.Debit</td>
                        <td>@pur.Credit</td>
                        <td>@pur.Balance</td>
                         
                        

                    </tr>
                }
                }
            </tbody>
        </table>
    </div>
</div>
@*end of grid*@

Corporate/Views/Accounting/PaymentDetail.cshtml
@using Corporate.ViewModel;
@model IEnumerable<PaymentVM>

@{
    ViewBag.Title = "Payment Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header id="headerz1">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="BGHeader"><span class="glyphicon glyphicon-pawn" aria-hidden="true"></span>Payment Details</h2>
            </div>
        </div>
    </div>

</header>

@*start of grid*@
<div class="panel panel-default">
    <div class="panel-heading text-center">
        <h3 class="panel-title"><b><u>Payment Detail</u></b></h3>
       
    </div>
    <div class="panel-body ">

        <table class="table table-responsive  table-hover">
            <thead>
               <tr><th>Recipt No</th><th>@Request.QueryString["RecieptID"]</th><th></th><th></th><th>Order date</th><th>@Request.QueryString["Date"]</th></tr>
                <tr>
                     <th>Date</th>
                    <th>Payment Mode</th>
                    <th>Amount</th>
                    <th>Details</th>
                    <th>Recieving Firm</th>
                    <th>Given by</th>  
                </tr>
                
            </thead>
            <tbody>
               @foreach (PaymentVM pur in @Model)
                {

                    <tr>
                        
                        <td>@pur.PaymentDate</td>
                        <td>@pur.PaymentType</td>
                        <td>@pur.PaymentAmount</td>
                        <td>@pur.Reference</td>
                        <td>@pur.Firm</td>
                       <td>@pur.CreatedBy</td>
                    </tr>
                   
                }  
            </tbody>
        </table>
    </div>
</div>
@*end of grid*@



<p>
   
    
    @Html.ActionLink(
    "Go to Payments", //linkText
    "Payment", //actionName
    "Accounting", //controllerName
     null, //routeValues
     null //htmlAttributes
)
<b>|</b>

   
    
    @Html.ActionLink(
    "Go to Ledger", //linkText
    "Index", //actionName
    "Accounting", //controllerName
     null, //routeValues
     null //htmlAttributes
)
</p>